services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: nutriscan
      POSTGRES_USER: nutriuser
      POSTGRES_PASSWORD: nutripass
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=nutriscan
      - DB_USER=nutriuser
      - DB_PASSWORD=nutripass
      - DB_HOST=db
      - DB_PORT=5432
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
