# Generated by Django 5.1.6 on 2025-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
